extends Node2D


@onready var enemySpawners = $Spawner/Enemy
@onready var objectSpawners = $Spawner/Object

func _ready() -> void:
	var enemySpawnersArray = enemySpawners.get_children()
	for i in enemySpawners.get_children():
		i.enabled = false
		enemySpawnersArray.shuffle()
	
	enemySpawnersArray[0].enabled = true
	enemySpawnersArray[1].enabled = true
	enemySpawnersArray[2].enabled = true
	enemySpawnersArray[3].enabled = true
	enemySpawnersArray[4].enabled = true
	#for i in enemySpawnersArray:
		#i.enabled = true
	

func spawnEnemies():
	for spawner in enemySpawners.get_children():
		spawner.spawn($Enemys)

func spawnObjects():
	for spawner in objectSpawners.get_children():
		spawner.spawn($Objects)
