extends Control

@onready var moneyResultLabel = $CenterContainer/VBoxContainer/HBoxContainer/MoneyResult
@onready var healthResultLabel = $CenterContainer/VBoxContainer/HBoxContainer2/HealthResult

@onready var succesLabel = $CenterContainer/VBoxContainer/VBoxContainer/SUCCESLabel
@onready var failureLabel = $CenterContainer/VBoxContainer/VBoxContainer/FAILURELabel

func _ready() -> void:
	if G.extracted:
		succesLabel.show()
		failureLabel.hide()
	moneyResultLabel.text = str(G.money)
	healthResultLabel.text = str(G.lastHealth)
		


func _on_home_button_button_up() -> void:
	get_parent().loadStartMenu()
